#!/bin/bash

nightlight(){
    if [[ $(gsettings get org.gnome.settings-daemon.plugins.color night-light-enabled) == "true" ]]; 
    then gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled false; 
    else gsettings set org.gnome.settings-daemon.plugins.color night-light-enabled true; 
    fi
}

if [ "$1" == "nl" ]
then
  nightlight
else
 echo -e "Usage : ./aus \$arg\n\$arg = nl -> enable/disable nightlight"
fi

